services:
  api:
    container_name: odoo-integration
    labels:
      container_group: odoo-integration
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .configs/.env.api
    ports:
      - "8080:8080"
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8080"

  postgres:
    image: postgres:17.5
    restart: unless-stopped
    volumes:
      - ./.configs/create_db.sh:/docker-entrypoint-initdb.d/create_db.sh
    ports:
      - "5433:5432"
    env_file:
      - .configs/.env.postgres
